import { Rubik } from 'next/font/google'
import './globals.css'

// components
import Navbar from './components/Navbar/component'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Next CC',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <header>
          <Navbar />
        </header>
        {children}
      
      </body>
    </html>
  )
}
